# ANSWER SECTION 

In [1]:
import torch
import numpy as np

# ---- SECTION 1 ANSWERS ----

In [2]:
a1 = torch.tensor([1, 2, 3, 4])

a2 = torch.full((2, 3), 5)

array = np.array([10,20,30])
a3 = torch.from_numpy(array)
print(a3.dtype)

a4 = torch.zeros(3, 3)

a5 = torch.rand(2, 2)

torch.int64


# ---- SECTION 2 ANSWERS ----

In [3]:
t = torch.randn(3, 4)
print(t.shape)
print(t.ndim)

a7 = torch.tensor([1, 2, 3]).float()

a8 = torch.arange(6).reshape(3, 2)

a9 = torch.tensor(7)
print(a9.ndim)

torch.Size([3, 4])
2
0


# ---- SECTION 3 ANSWERS ----


In [4]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print(x + y)

A = torch.randn(2, 3)
B = torch.randn(3, 2)
print(torch.matmul(A, B))

z = torch.tensor([1, 2, 3])
print(z * 5)

print(z.float().mean())

print(z.max())

tensor([5, 7, 9])
tensor([[ 0.5683, -0.1522],
        [-0.6677, -3.1989]])
tensor([ 5, 10, 15])
tensor(2.)
tensor(3)


# ---- SECTION 4 ANSWERS ----


In [5]:
a = torch.tensor([[1], [2], [3]])
b = torch.tensor([[10, 20, 30]])
print(a + b)

print(z + 10)

# Broadcasting automatically expands smaller tensors
# to match larger tensor shapes for operations

tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
tensor([11, 12, 13])


# ---- SECTION 5 ANSWERS ----


In [6]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

y.backward()
print(x.grad)

# Gradients tell how much to change weights
# to reduce loss during training

tensor(4.)


---

# ADVANCE QUESTION ANSWERS

# --- SECTION 1 ANSWERS ---

In [7]:
t = torch.tensor([10, 20, 30, 40, 50])
print(t[2])

print(t[:3])

m = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(m[1,2])

print(m[:,1])

x = torch.tensor([1,2,3,4,5,6])

print(x[x % 2 == 0])

x[x > 3] = 0

print(x)

print((x == 4).any())

print((x > 2).sum())

tensor(30)
tensor([10, 20, 30])
tensor(6)
tensor([2, 5, 8])
tensor([2, 4, 6])
tensor([1, 2, 3, 0, 0, 0])
tensor(False)
tensor(1)


# --- SECTION 2 ANSWERS ---

In [8]:
a = torch.tensor([1,2,3])
print(a.unsqueeze(0))

print(a.unsqueeze(0).squeeze())

print(torch.randn(3,4).unsqueeze(1))

tensor([[1, 2, 3]])
tensor([1, 2, 3])
tensor([[[ 0.0817, -0.6970, -0.9645,  0.4623]],

        [[-2.1284,  2.0286,  1.5847, -0.0351]],

        [[-0.5092, -1.2405, -1.8695, -1.3806]]])


# --- SECTION 3 ANSWERS ---


In [9]:
s = torch.tensor([3,1,4,2])
print(torch.sort(s))

print(torch.argsort(s))

print(torch.sort(s, descending=True))

m2 = torch.tensor([[3,1],[2,4]])

print(torch.sort(m2, dim=1))

torch.return_types.sort(
values=tensor([1, 2, 3, 4]),
indices=tensor([1, 3, 0, 2]))
tensor([1, 3, 0, 2])
torch.return_types.sort(
values=tensor([4, 3, 2, 1]),
indices=tensor([2, 0, 3, 1]))
torch.return_types.sort(
values=tensor([[1, 3],
        [2, 4]]),
indices=tensor([[1, 0],
        [0, 1]]))


# ---- SECTION 4 ANSWERS ---


In [10]:
a = torch.tensor([1,2])
b = torch.tensor([3,4])

print(torch.stack([a,b], dim=0))

print(torch.stack([a,b], dim=1))

print(torch.cat([a,b]))


tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([1, 2, 3, 4])


# ---- SECTION 5 ANSWERS ---


In [11]:
f = torch.randn(2,3)
print(f.flatten())

# view needs contiguous memory
# reshape works even if memory not contiguous

p = torch.randn(2,3,4)


print(p.permute(2,1,0))

tensor([-1.3396,  0.7507,  0.7231,  0.1120,  0.4044,  0.0521])
tensor([[[ 1.0923,  0.7947],
         [ 1.7677, -1.7445],
         [-0.0741,  0.5259]],

        [[-0.7241,  1.0142],
         [-0.7419, -1.4056],
         [-0.4765,  0.9233]],

        [[-2.0293, -0.3034],
         [-0.5220,  1.2981],
         [ 0.3865, -0.1495]],

        [[-0.1793, -1.4999],
         [ 0.4366,  0.5148],
         [-0.3821, -0.4015]]])


# ---- SECTION 6 ANSWERS ----


In [12]:
mat = torch.randn(3,4)
print(mat.T)

print(torch.randn(2,3,4).permute(1,0,2))

tensor([[-1.4692,  1.1185,  0.8844],
        [-0.5253, -0.8662, -0.6125],
        [ 0.5384, -0.0925, -0.4533],
        [-0.3708, -0.5296,  1.9574]])
tensor([[[ 1.6071,  2.3109, -0.9648,  0.3058],
         [ 1.2890, -0.5383, -1.0988,  0.1659]],

        [[ 0.1234, -0.2285,  0.0184,  0.0629],
         [-1.6181,  1.5625, -0.2006,  0.5671]],

        [[-0.4869, -0.7730, -1.7457, -0.4589],
         [ 1.9557,  0.0450,  0.1468,  0.2931]]])


# GPU 

# ---- PRACTICE 1 ANSWER ----


In [13]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

a = torch.tensor([1, 2, 3])
a_gpu = a.to(device)
print(a_gpu, a_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


# ---- PRACTICE 2 ANSWER ----


In [14]:
b = torch.tensor([4.0, 5.0, 6.0], device=device)
b_cpu = b.cpu()
b_np = b_cpu.numpy()
print(b_np, type(b_np))

[4. 5. 6.] <class 'numpy.ndarray'>


# ---- PRACTICE 3 ANSWER ----


In [15]:
np_arr = np.array([1, 2, 3, 4])
t = torch.from_numpy(np_arr)
t_gpu = t.to(device)
print(t_gpu)

tensor([1, 2, 3, 4], device='cuda:0')


# ---- PRACTICE 4 ANSWER ----


In [16]:
np_x = np.array([10, 20, 30], dtype=np.int32)
t_x = torch.from_numpy(np_x)
t_x[0] = 999
print(np_x)  # NumPy changes because memory is shared

[999  20  30]


# ---- PRACTICE 5 ANSWER ----


In [17]:
gpu_tensor = torch.tensor([1, 2, 3], device=device)


gpu_tensor.cpu().numpy()

array([1, 2, 3])